version: '2.1'
services:
  ecs:
    image: amaysim/ecs-utils:local
    build: .
    volumes:
      - .:/srv/app:Z
  pylint:
    image: clburlison/pylint
    entrypoint: ["pylint"]
    volumes:
      - .:/code:Z
    network_mode: "none"
    working_dir: /code
  flake8:
    image: eeacms/flake8
    volumes:
      - .:/code:Z
    network_mode: "none"
    working_dir: /code
  cookiecutter:
    image: amaysim/cookiecutter:1.5.1
    env_file: .env
    volumes:
      - ~/.ssh:/root/.ssh:Z
      - .:/srv/app:Z
  cfn-python-lint:
    image: amaysim/cfn-python-lint:latest
    network_mode: "none"
    entrypoint: ''
    env_file: .env
    working_dir: /srv/app
    volumes:
      - .:/srv/app:Z
